### ISSUE TITLE
Document X-Forwarded-Host automatic header

### ISSUE THREAD

**Issue by JeroenBakker** [ngrok/ngrok-docs#463]
Hi there,

The documentation for the HTTP endpoints [mentions](https://ngrok.com/docs/http/#upstream-headers) two automatic headers:  

- `X-Forwarded-For`
- `X-Forwarded-Proto`

But I also see the `X-Forwarded-Host` header being added automatically, populated with a value such as `c55e-217-63-79-110.ngrok-free.app`

The documentation for the request header module [mentions](https://ngrok.com/docs/http/request-headers/#automatic-headers) that the automatic headers can be removed using that module:

>Regardless of whether you enable the request headers module or not, [ngrok adds default headers to every HTTP request](https://ngrok.com/docs/http/#upstream-headers).
>
>You may remove these default headers with the request headers module.

And while this appears to be true for the 2 mentioned headers, I can't seem to remove the `X-Forwarded-Host` header.

I'm not sure if this is an issue with the documentation or ngrok itself (either the agent CLI or some other part).

Unrelated to the docs, I'm running into this problem because the service I'm forwarding requests to can't process this exact header, resulting in a 500 response.

If you want to reproduce the behaviour in order to describe it more clearly in the docs, simply running this will show the header in all requests:
```shell
ngrok http example.com:443 --host-header example.com
```

**Comment by inconshreveable** [comment]
@JeroenBakker nice catch, thank you so much for filing this issue. you're 100% right that we're missing documentation on this behavior. `x-forwarded-host` isn't an automatic header, it only appears when you rewrite the `host` header.

you can work around this problem for the moment with this command instead:

```
ngrok http example.com:443 --request-header-add 'host: example.com' --request-header-remove 'host'
```

this command works when `--host-header` does not because of an implementation detail about how `--host-header` is implemented. it will be fixed in the next release of the ngrok agent. and then they will both work equivalently.

we'll make sure to get this behavior documented as well. thank you again!

**Comment by JeroenBakker** [comment]
Thanks for the quick response, the workaround is exactly what I needed!

**Comment by JeroenBakker** [comment]
Just ran into this issue again (of the downstream service not accepting the `X-Forwarded-Host`), 
and since I couldn't remember how this worked I came here to remind myself what was going on.

Luckily `--request-header-remove 'x-forwarded-host'` works with `--host-header` now so the workaround is no longer needed, and I see the docs mention this header now as well.

So I think this issue can be closed 🙂
